# Generated by Django 4.0.2 on 2022-02-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Dashboard',
        ),
    ]
